import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { ReactElement } from "react";
import Footer from "@/components/Footer";
import Destiny from "@/components/svg/destiny.svg";

const inter = Inter({ subsets: ["latin"] });

type TAdditionalLink = {
  url: string;
  type: string;
};

type TTool = {
  name: string;
  url: string;
  description: ReactElement | string;
  additionalLinks?: Array<TAdditionalLink>;
  image: string;
};

const tools: Array<TTool> = [
  {
    name: "BRAYTECH",
    url: "https://bray.tech/",
    image: "/images/braytech.png",
    description: (
      <>
        Explore Destiny through Braytech for sweet gains and insight into your
        fights against the forces of Darkness
      </>
    ),
    additionalLinks: [
      {
        url: "https://twitter.com/BraytechHelp",
        type: "twitter",
      },
    ],
  },
  {
    name: "Destiny Item Manager",
    url: "https://app.destinyitemmanager.com/",
    image: "/images/dim.png",
    description: (
      <>
        Control Your Items Your Way.
        <br />
        Swap items, check stats, and build the loadout to Become Legend with
        Destiny Item Manager.
      </>
    ),
  },
  {
    name: "D2Checkpoint.com",
    url: "https://d2checkpoint.com/",
    image: "/images/d2checkpoint.png",
    description: <>Find checkpoits for raid and dungeon encouters</>,
  },
  {
    name: "light.gg",
    url: "https://www.light.gg/",
    image: "/images/light.gg.png",
    description:
      "home of the most powerful Destiny 2 Database & Tools on the Internet",
  },
  {
    name: "engram.blue",
    url: "https://engram.blue/",
    image: "/images/engram.blue.png",
    description: (
      <>
        Track your progress for weapon pattern unlocks and crafted weapon levels
        <br />
        King’s Fall Deepsight puzzle helper
        <br />
        Vow of the Disciple Deepsight puzzle helper
        <br />
        How well do you know your vault?
        <br />
        Browse Wishlist recommendations for weapons
      </>
    ),
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Destiny 2 Toolbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-white py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl lg:mx-0">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                <Destiny
                  fill="#000"
                  style={{
                    width: "60px",
                    height: "60px",
                  }}
                />
                Destiny 2 Toolbox
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                A list of valuable tools for every Guardian.
              </p>
            </div>
            <ul
              role="list"
              className="mx-auto mt-20 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3"
            >
              {tools.map((tool) => (
                <li key={tool.name}>
                  <a href={tool.url} target="_blank">
                    <img
                      className="aspect-[5/4] w-full rounded-2xl object-cover"
                      src={tool.image}
                      alt={tool.name}
                    />
                  </a>
                  <h2 className="mt-6 text-3xl font-bold leading-8 tracking-tight text-gray-900">
                    <a href={tool.url} target="_blank">
                      {tool.name}
                    </a>
                  </h2>
                  <p className="text-base mt-6 leading-7 text-gray-600">
                    {tool.description}
                  </p>
                  {/* <ul role="list" className="mt-6 flex gap-x-6">
                    <li>
                      <a
                        href={tool.url}
                        className="text-gray-400 hover:text-gray-500"
                      >
                        <span className="sr-only">Twitter</span>
                        <svg
                          className="h-5 w-5"
                          aria-hidden="true"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path d="M6.29 18.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0020 3.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.073 4.073 0 01.8 7.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 010 16.407a11.616 11.616 0 006.29 1.84" />
                        </svg>
                      </a>
                    </li>
                  </ul> */}
                </li>
              ))}
            </ul>
          </div>
          <Footer />
        </div>
      </main>
    </>
  );
}
