const defineTools = <const T extends readonly TTool[]>(tools: T) => tools;

export const tools = defineTools([
	{
		slug: "pete-carsons",
		name: "Vault Of Cars",
		url: "https://petecarsons.com/",
		requiresLogin: false,
		description:
			"Do you have what it takes to face Pete Carsons in the Vault of Cars and stop him from purchasing all of the remaining cars in The Last City?",
		active: true,
		category: ["community"],
		crawl: true,
	},
	{
		slug: "starfarer",
		name: "Reminder",
		url: "https://www.light.gg/db/items/472776702/starfarer-7m/",
		requiresLogin: false,
		description: "Equip the Starfarer 7M for extra dawning spirit",
		active: false,
		category: [],
		crawl: false,
	},
	{
		slug: "braytech",
		name: "BRAYTECH",
		url: "https://bray.tech/",
		requiresLogin: true,
		description:
			"Explore Destiny through Braytech for sweet gains and insight into your fights against the forces of Darkness",
		additionalLinks: [
			"https://www.threads.net/@braytechapp",
			"https://discord.com/invite/8jESWWX",
			"https://www.patreon.com/braytech",
			"https://www.paypal.com/paypalme/braytechltd",
		],
		active: true,
		category: ["inventory", "statistics", "progress", "lore"],
		crawl: true,
	},
	{
		slug: "dim",
		name: "Destiny Item Manager",
		url: "https://app.destinyitemmanager.com/",
		requiresLogin: true,
		description:
			"Control Your Items Your Way.<br />Swap items, check stats, and build the loadout to Become Legend with Destiny Item Manager.",
		additionalLinks: [
			"https://mstdn.games/@ThisIsDIM",
			"https://www.reddit.com/r/DestinyItemManager/",
			"https://github.com/DestinyItemManager/DIM/",
			"https://discord.com/invite/UK2GWC7",
		],
		active: true,
		category: ["inventory", "progress"],
		wait: ".store-header, .character",
		crawl: true,
	},
	{
		slug: "destiny-report",
		name: "destiny.report",
		url: "https://destiny.report/",
		description:
			"destiny.report is a fast tool for exploring Destiny 2 weapons. Search the entire arsenal by name, perk, archetype, damage type, stat, source, and more, then dig into any weapon's perks, stats, and rolls.<br />The aim is accurate, up-to-date weapon data that's quick to search.",
		requiresLogin: false,
		additionalLinks: [],
		category: ["data"],
		active: true,
		crawl: true,
	},
	{
		slug: "armor-picker",
		name: "D2ArmorPicker",
		url: "https://d2armorpicker.com/#/",
		description:
			"D2ArmorPicker (or short D2AP) is a small web-app to quickly find armor that fits your desired stat requirements. It uses the armor in your vault, inventory and postmaster, calculates every possible variation and shows only those that fulfill the given requirements.",
		requiresLogin: true,
		additionalLinks: [
			"https://twitter.com/MijagoCoding/",
			"https://ko-fi.com/mijago",
			"https://discord.com/invite/7eFjeVbz2V",
		],
		active: true,
		category: ["inventory"],
		crawl: true,
	},
	{
		slug: "checkpoint",
		name: "D2Checkpoint.com",
		url: "https://d2checkpoint.com/",
		requiresLogin: false,
		description: "Find checkpoints for raid and dungeon encounters",
		additionalLinks: [
			"https://discord.com/invite/d2checkpoint",
			"https://ko-fi.com/d2checkpoint",
		],
		active: true,
		category: ["community"],
		crawl: true,
	},
	{
		slug: "lightgg",
		name: "light.gg",
		url: "https://www.light.gg/",
		requiresLogin: false,
		description:
			"home of the most powerful Destiny 2 Database & Tools on the Internet",
		additionalLinks: [
			"https://twitter.com/lightdotgg",
			"https://discord.com/invite/pmHRd5U",
			"https://www.light.gg/account/patreon",
			"https://www.youtube.com/c/lightggdb",
		],
		active: true,
		category: ["analysis", "statistics", "community", "data"],
		crawl: true,
	},
	{
		slug: "foundry",
		name: "Foundry",
		url: "https://d2foundry.gg/",
		requiresLogin: true,
		description: "Your companion to Destiny 2 weapons and perks.",
		active: false,
		additionalLinks: [
			"https://bsky.app/profile/gothfem.me",
			"https://discord.com/invite/dzW2DZBBQH",
			"https://ko-fi.com/gothfemme",
		],
		category: ["analysis", "statistics", "community", "data"],
		crawl: false,
	},
	{
		slug: "engram-blue",
		name: "engram.blue",
		url: "https://engram.blue/",
		requiresLogin: true,
		description:
			"Track your progress for weapon pattern unlocks and crafted weapon levels<br />King’s Fall Deepsight puzzle helper<br />Vow of the Disciple Deepsight puzzle helper<br />How well do you know your vault?<br />Browse Wishlist recommendations for weapons",
		additionalLinks: ["https://discord.com/invite/Kfuqcw4msG"],
		active: true,
		category: ["analysis", "tools"],
		crawl: true,
	},
	{
		slug: "recipes",
		name: "Destiny Recipes",
		description:
			"You can find here a list of helpful tools for Destiny 2. I like to call them recipes for success.",
		url: "https://destinyrecipes.com/",
		requiresLogin: true,
		additionalLinks: [
			"https://twitter.com/D2Recipes",
			"https://discord.com/invite/cX8R6wPRB8",
			"https://ko-fi.com/alanbalbo",
		],
		active: true,
		category: ["analysis", "tools"],
		crawl: true,
	},
	{
		slug: "checklist",
		name: "D2 Checklist",
		url: "https://www.d2checklist.com/",
		requiresLogin: true,
		description:
			"D2Checklist uses the Bungie API to help make achieving your goals in Destiny easier and more fun.",
		additionalLinks: [
			"https://www.reddit.com/r/destinychecklistnet/",
			"https://github.com/dcaslin/d2-checklist/",
			"https://twitter.com/D2Checklist",
			"https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=VBASBDZD7HAHS",
		],
		active: false,
		category: ["analysis", "tools"],
		crawl: true,
	},
	{
		slug: "ishtar-collective",
		name: "Ishtar Collective",
		url: "https://www.ishtar-collective.net/",
		requiresLogin: false,
		description:
			"Our goal is to collect, organize and summarize any information that could be useful to the research being carried out by Ishtar Collective personnel.",
		additionalLinks: [
			"https://twitter.com/IshtarColl",
			"https://www.patreon.com/ishtarcollective",
			"https://commons.ishtar-collective.net/",
			"https://errata.ishtar-collective.net/",
			"https://discord.com/invite/R33Wncn",
			"https://ishtar-collective.tumblr.com/",
		],
		active: true,
		category: ["lore", "data"],
		crawl: true,
	},
	{
		slug: "raid-report",
		name: "raid.report",
		url: "https://raid.report",
		description: "Show raid completions and stats",
		requiresLogin: false,
		additionalLinks: [
			"https://twitter.com/RaidReport",
			"https://dungeon.report/",
		],
		active: true,
		category: ["statistics", "community", "progress"],
		crawl: true,
	},
	{
		slug: "lost-sector-report",
		name: "D2 Lost Sector Report",
		url: "https://d2lostsector.report/",
		description: "Your daily Destiny 2 Expert & Master Lost Sector report. ",
		requiresLogin: false,
		additionalLinks: [
			"https://bsky.app/profile/d2lostsector.report",
			"https://twitter.com/D2LostSector",
			"https://www.twitch.tv/d2lostsector",
			"https://discord.com/invite/d2-lost-sector-report-975760471577722920",
		],
		active: true,
		category: ["statistics", "community", "progress"],
		crawl: true,
	},
	{
		slug: "today-in-destiny",
		name: "TodayInDestiny",
		url: "https://todayindestiny.com/",
		description: "What should we do today Guardian?",
		requiresLogin: false,
		additionalLinks: [
			"https://www.patreon.com/todayindestiny",
			"https://ko-fi.com/JpDeathBlade",
		],
		active: false,
		category: ["statistics", "community", "progress", "tools"],
		crawl: true,
	},
	{
		slug: "synergy",
		name: "D2 Synergy",
		url: "https://d2synergy.com/",
		description:
			"Synergy groups progressions together and gives recommendations for optimal progression.",
		requiresLogin: true,
		additionalLinks: [
			"https://github.com/dev-brendanprice/D2-Synergy",
			"https://twitter.com/_brendanprice",
		],
		active: false,
		category: ["progress", "tools"],
		crawl: true,
	},
	{
		slug: "emblem-collector",
		name: "Destiny Emblem Collector",
		url: "https://destinyemblemcollector.com/",
		requiresLogin: false,
		description: "Browse, track, and collect every Destiny 2 emblem",
		additionalLinks: ["https://x.com/emblemcollector"],
		active: true,
		category: ["inventory", "data"],
		crawl: true,
	},
	{
		slug: "aegis",
		name: "Aegis Spreadsheets",
		url: "https://drive.google.com/drive/folders/1AL3GM6rSSrm4LtSZeayxpSUsvSJdsiU3",
		description:
			"Boss Damage, Boss Health and endgame analysis. Exhaustive and detailed breakdown of all possible damage numbers",
		requiresLogin: false,
		additionalLinks: [
			"https://www.youtube.com/@TheAegisRelic",
			"twitch.tv/TheAegisRelic",
		],
		active: true,
		category: ["analysis", "data"],
		crawl: true,
	},
	{
		slug: "where-is-xur",
		name: "Where is Xur?",
		url: "https://whereisxur.com/",
		description: "Nobody ever asks “How is Xur?”",
		requiresLogin: false,
		additionalLinks: [
			"https://twitter.com/xurwatchlive",
			"https://www.twitch.tv/whereisxur",
			"https://www.youtube.com/whereisxurnow",
			"https://discord.com/invite/ZgudXPZ",
		],
		active: false,
		category: ["tools"],
		crawl: true,
	},
	{
		slug: "sundered-doctrine",
		name: "Sundered Doctrine",
		url: "/sundered-doctrine",
		requiresLogin: false,
		description: "Sundered Doctrine Resources",
		active: true,
		category: [],
		crawl: false,
	},
	{
		slug: "bungo",
		name: "bungie.net",
		url: "https://www.bungie.net/7",
		description: "the home of Destiny2",
		requiresLogin: true,
		additionalLinks: [
			"https://twitter.com/bungie",
			"https://twitter.com/destinythegame",
		],
		active: true,
		category: ["statistics", "community", "progress", "tools", "inventory"],
		crawl: true,
	},
]);

export type TToolSlug = (typeof tools)[number]["slug"];

export const quickLinks: TQuickLink[] = [
  {
		url: "https://docs.google.com/spreadsheets/d/1WDj-vExf9c982PVc1nRRfjadhkcZFqa7nv14cCMI8C8/htmlview#gid=341150307",
		description: "ALL Monument of Triumph Legendary Loot Sources",
	},
  {
		url: "https://www.reddit.com/r/DestinyTheGame/s/ClgN59WhVB",
		description: "all free emblem codes",
	},
];

export const changelog: TChangelogEntry[] = [
	{
		date: "2026-07-13",
		text: "added destiny.report, retired whereisxur.com",
		slug: "destiny-report",
	},
	{
		date: "2026-07-10",
		text: "added Postmaster feature for quick links.",
	},
	{
		date: "2026-07-08",
		text: "added vault of cars",
		slug: "pete-carsons",
	},
	{
		date: "2026-07-08",
		text: "added destinyemblemcollector.com",
		slug: "emblem-collector",
	},
];
