/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SunderedDoctrineRouteImport } from './app/sundered-doctrine'
import { Route as IndexRouteImport } from './app/index'

const SunderedDoctrineRoute = SunderedDoctrineRouteImport.update({
  id: '/sundered-doctrine',
  path: '/sundered-doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sundered-doctrine': typeof SunderedDoctrineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sundered-doctrine': typeof SunderedDoctrineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sundered-doctrine': typeof SunderedDoctrineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sundered-doctrine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sundered-doctrine'
  id: '__root__' | '/' | '/sundered-doctrine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SunderedDoctrineRoute: typeof SunderedDoctrineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sundered-doctrine': {
      id: '/sundered-doctrine'
      path: '/sundered-doctrine'
      fullPath: '/sundered-doctrine'
      preLoaderRoute: typeof SunderedDoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SunderedDoctrineRoute: SunderedDoctrineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
